# Generated by Django 5.2.3 on 2025-07-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.FileField(blank=True, upload_to='imagens_projetos', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologia',
            field=models.CharField(max_length=20, verbose_name='Tecnologia'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=180, verbose_name='Título'),
        ),
    ]
