# Generated by Django 5.2.3 on 2025-07-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome Categoria'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=60, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='corpo',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='corpo',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='ultima_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
    ]
